Clean and expose r
fellstat/ernm pull request #3
Opened 2024-04-28 19:51 UTC by duncan-clark

package builds cleanly

2024-04-29 17:32 UTC, ifellows requested changes

2024-04-29 17:32 UTC, ifellows commented on src/Model.h
> +    void dyadUpdateR(int from, int to){
not to be pedantic, but what happens if from or to are less than 1?

2024-04-29 17:32 UTC, ifellows commented on src/Model.h
> +        this->dyadUpdateR((from-1),(to-1));
do you mean to call dyadUpdate not dyadUpdateR?

2024-04-30 16:29 UTC, duncan-clark commented
rebased so can automerge

2024-04-30 16:37 UTC, ifellows commented
So ready for merge?

2024-05-01 19:31 UTC, merged